# Generated by Django 4.2.7 on 2023-12-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyIncomeExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('food', models.IntegerField(blank=True, null=True)),
                ('rice', models.IntegerField(blank=True, null=True)),
                ('bread_cereal', models.IntegerField(blank=True, null=True)),
                ('meat', models.IntegerField(blank=True, null=True)),
                ('fish', models.IntegerField(blank=True, null=True)),
                ('fruits', models.IntegerField(blank=True, null=True)),
                ('vegetables', models.IntegerField(blank=True, null=True)),
                ('hotels', models.IntegerField(blank=True, null=True)),
                ('alcohol', models.IntegerField(blank=True, null=True)),
                ('tobacco', models.IntegerField(blank=True, null=True)),
                ('clothing', models.IntegerField(blank=True, null=True)),
                ('housing', models.IntegerField(blank=True, null=True)),
                ('medical', models.IntegerField(blank=True, null=True)),
                ('transport', models.IntegerField(blank=True, null=True)),
                ('communication', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('miscellaneous', models.IntegerField(blank=True, null=True)),
                ('occasions', models.IntegerField(blank=True, null=True)),
                ('farming', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
